--CREATE SEQUENCE user_id_seq;

--DROP TABLE users;
--
--CREATE TABLE users (
--    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    user_name varchar(40) NOT NULL,
--    password varchar(80) NOT NULL
--);
--
--INSERT INTO users VALUES (DEFAULT, 'admin', '$2b$10$Xz4Sav15kcnzQEDu31v0Pe9fJ2WDfdFxtzMrxJSu1TgPvcdLDVCy2');

UPDATE users
SET    first_name = 'Michael'
WHERE  id = 123
AND    first_name IS DISTINCT FROM 'Michael';

SELECT * FROM users
